### ISSUE TITLE
KaiLv/DBPedia can not process successfully

### ISSUE THREAD

**Issue by moonmengmeng** [KaiLv69/UDR#3]
KaiLv/DBPedia can not be success loaded in the train script and its download in huggingface is only 2 while others all more than 10. I think this dataset may in some error although it can be loaded by dataset = load_dataset("KaiLv/DBPedia"):

error:InstantiationException: Error in call to target 'dpr.data.biencoder_data.EPRDataset':
FileNotFoundError("Couldn't find a dataset script at
/data/jiaweilu/UDR-main/exps/bs128_grad-acc4_rk4_seed1208/iter0/logs/KaiLv/UDR_DBPedia/UDR_DBPedia.py or any data file in the same
directory. Couldn't find 'KaiLv/UDR_DBPedia' on the Hugging Face Hub either: FileNotFoundError: Dataset 'KaiLv/UDR_DBPedia' doesn't
exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`.")

**Comment by KaiLv69** [comment]
`Dataset 'KaiLv/UDR_DBPedia' doesn't exist on the Hub` is weird since `it can be loaded by dataset = load_dataset("KaiLv/DBPedia")`. Could you please give more detailed traceback to locate the problem.

**Comment by moonmengmeng** [comment]
I think error may be at here
│ /data/jiaweilu/UDR-main/DPR/dpr/data/biencoder_data.py:1090 in get_dbpedia                       │
│                                                                                                  │
│   1087                                                                                           │
│   1088 @dataset_dict.add("dbpedia")                                                              │
│   1089 def get_dbpedia():                                                                        │
│ ❱ 1090 │   dataset = load_dataset("KaiLv/UDR_DBPedia")                                           │
│   1091 │   return dataset                                                                        │
│   1092                                                                                           │
│   1093 @dataset_dict.add("yahoo")

**Comment by KaiLv69** [comment]
uh..... I checked the spelling again and found that I missing the prefix `UDR_`. I've renamed the dataset in HF and it should be fine now.
