### ISSUE TITLE
udr_go dataset error

### ISSUE THREAD

**Issue by moonmengmeng** [KaiLv69/UDR#4]
**when i run the following code**

from datasets import load_dataset
dataset = load_dataset("KaiLv/UDR_Go")

**i got error:** 

  File "/home/jiaweilu/anaconda3/envs/udr6/lib/python3.10/site-packages/datasets/builder.py", line 1879, in _prepare_split_single
    for _, table in generator:
  File "/home/jiaweilu/anaconda3/envs/udr6/lib/python3.10/site-packages/datasets/packaged_modules/parquet/parquet.py", line 75, in _generate_tables
    for batch_idx, record_batch in enumerate(
  File "pyarrow/_parquet.pyx", line 1323, in iter_batches
  File "pyarrow/error.pxi", line 115, in pyarrow.lib.check_status
OSError: Couldn't deserialize thrift: TProtocolException: Invalid data
Deserializing page header failed.

**other dataset like UDR_Java do not occur this error**

**Comment by KaiLv69** [comment]
Hi, you may sample UDR_Go here: https://github.com/KaiLv69/UDR/blob/5fb1efbe75359d2a46f134a61ca391f55ee29120/sample_dataset.py#L1229

**Comment by moonmengmeng** [comment]
**I think it does not work for me because in the code:**
def sample_go():
    base_url = "/nvme/xnli/lk_code/exps/rtv_icl/data/code_comment/dataset/go/"
    dataset = load_dataset("json",
                           data_files={"train": base_url + "train.jsonl", "validation": base_url + "valid.jsonl",
                                       'test': base_url + "test.jsonl"})

**you have dataset at /nvme/xnli/lk_code/exps/rtv_icl/data/code_comment/dataset/go/
but i only can get huggingface dataset and can not get the file train.jsonl, can you fix the dataset on huggingface so that i can load it? thank you**

**Comment by moonmengmeng** [comment]
or how can i delete some of the dataset and use rest of them to train the model. I think only modify scripts/train_iter0.sh is not enough, may some files  in DPR should be modify. thank you for your reply

**Comment by moonmengmeng** [comment]
![image](https://github.com/KaiLv69/UDR/assets/98024616/065400c4-4324-4ebb-a0f3-60fc1494ef16)
this is the error on huggingface

**Comment by KaiLv69** [comment]
The dataset on HF should be fine now.
<img width="1254" alt="image" src="https://github.com/KaiLv69/UDR/assets/39761308/a6414d9b-c0de-49e9-9471-b7c4799ea886">

**Comment by moonmengmeng** [comment]
great. it really helps me a lot. Thank you!!!!!!!!
