### ISSUE TITLE
I have a question about the candidate number

### ISSUE THREAD

**Issue by moonmengmeng** [KaiLv69/UDR#5]
In the paper Scoring Candidates Num (K)=50, Training Candidates Num (l)=8. Why aren't they equal in number, and how to choose l out of K.

**Comment by KaiLv69** [comment]
I = 50 took up too much memory and is not that beneficial to training. The choosing of I can be referred here https://github.com/KaiLv69/UDR/blob/5fb1efbe75359d2a46f134a61ca391f55ee29120/DPR/train_dense_encoder.py#L899

**Comment by moonmengmeng** [comment]
In your paper it says "For computational efficiency, we first update candidates and score Z∗ at each iteration, and then randomly sample l of Z∗ and rank them at each training step. In summary, Algorithm 1 shows the UDR’s overall training procedure." But i'm confused about why not randomly sample l first and score them rather than score first, the other 42 samples are scored but do not used. That's what I'm confused about. Thank you for your reply
