### ISSUE TITLE
when i run the testing script i got a strange error about inference.py

### ISSUE THREAD

**Issue by moonmengmeng** [KaiLv69/UDR#6]
InstantiationException: Error in call to target 'src.dataset_readers.few_shot_dsr.FewShotDatasetReader':
NameError("name 'load_dataset' is not defined")
full_key: dataset_reader
files like agnews_dpr_index_0 or dr_data_agnews_test can be successfully generated but the inference script can not process successfully more over add code "from datasets import load_dataset" to the  inference.py script can not solve the problem

**Comment by moonmengmeng** [comment]
solved

**Comment by sumyeongahn** [comment]
I got the same issue. 
Could you let me know how to solve that issue??
